export const LOCATIONS = [
    { from: "New York, NY", to: "Los Angeles, CA", distance_miles: 2790 },
    { from: "Chicago, IL", to: "Dallas, TX", distance_miles: 967 },
    { from: "Miami, FL", to: "Atlanta, GA", distance_miles: 663 },
    { from: "Seattle, WA", to: "San Francisco, CA", distance_miles: 807 },
    { from: "Denver, CO", to: "Las Vegas, NV", distance_miles: 748 },
    { from: "Houston, TX", to: "Phoenix, AZ", distance_miles: 1175 },
    { from: "Boston, MA", to: "Washington, DC", distance_miles: 440 },
    { from: "Detroit, MI", to: "Minneapolis, MN", distance_miles: 694 },
    { from: "New York, NY", to: "Chicago, IL", distance_miles: 790 },
    { from: "Los Angeles, CA", to: "San Francisco, CA", distance_miles: 383 },
    { from: "Philadelphia, PA", to: "Atlanta, GA", distance_miles: 864 },
    { from: "San Diego, CA", to: "San Francisco, CA", distance_miles: 502 },
    { from: "Orlando, FL", to: "New York, NY", distance_miles: 1080 },
    { from: "Miami, FL", to: "New Orleans, LA", distance_miles: 1090 },
    { from: "Dallas, TX", to: "Chicago, IL", distance_miles: 967 },
    { from: "Denver, CO", to: "Chicago, IL", distance_miles: 1000 },
    { from: "Seattle, WA", to: "Denver, CO", distance_miles: 1300 },
    { from: "Los Angeles, CA", to: "Denver, CO", distance_miles: 1015 },
    { from: "Houston, TX", to: "Chicago, IL", distance_miles: 1080 },
    { from: "Phoenix, AZ", to: "Los Angeles, CA", distance_miles: 373 },
    { from: "San Francisco, CA", to: "Seattle, WA", distance_miles: 807 },
    { from: "New York, NY", to: "Boston, MA", distance_miles: 215 },
    { from: "Atlanta, GA", to: "Chicago, IL", distance_miles: 716 },
    { from: "Miami, FL", to: "Tampa, FL", distance_miles: 280 },
    { from: "Philadelphia, PA", to: "Chicago, IL", distance_miles: 759 },
    { from: "Dallas, TX", to: "Los Angeles, CA", distance_miles: 1435 },
    { from: "Denver, CO", to: "Phoenix, AZ", distance_miles: 855 },
    { from: "Houston, TX", to: "Atlanta, GA", distance_miles: 810 },
    { from: "Seattle, WA", to: "Chicago, IL", distance_miles: 2060 },
    { from: "San Diego, CA", to: "Las Vegas, NV", distance_miles: 330 },
    { from: "New York, NY", to: "Washington, DC", distance_miles: 225 },
    { from: "Chicago, IL", to: "New Orleans, LA", distance_miles: 925 },
    { from: "Los Angeles, CA", to: "Houston, TX", distance_miles: 1540 },
    { from: "San Francisco, CA", to: "Los Angeles, CA", distance_miles: 383 },
    { from: "Miami, FL", to: "Houston, TX", distance_miles: 1180 },
    { from: "Atlanta, GA", to: "Dallas, TX", distance_miles: 780 },
    { from: "Philadelphia, PA", to: "Miami, FL", distance_miles: 1200 },
    { from: "Chicago, IL", to: "New York, NY", distance_miles: 790 },
    { from: "Houston, TX", to: "Phoenix, AZ", distance_miles: 1175 },
    { from: "San Diego, CA", to: "Phoenix, AZ", distance_miles: 355 },
    { from: "Seattle, WA", to: "San Diego, CA", distance_miles: 1250 },
    { from: "Boston, MA", to: "Chicago, IL", distance_miles: 980 },
    { from: "New York, NY", to: "Los Angeles, CA", distance_miles: 2790 },
    { from: "Dallas, TX", to: "Miami, FL", distance_miles: 1300 },
    { from: "Denver, CO", to: "Seattle, WA", distance_miles: 1300 },
    { from: "Los Angeles, CA", to: "Chicago, IL", distance_miles: 2015 },
    { from: "Phoenix, AZ", to: "Denver, CO", distance_miles: 855 },
    { from: "San Francisco, CA", to: "Phoenix, AZ", distance_miles: 750 },
    { from: "Houston, TX", to: "Los Angeles, CA", distance_miles: 1540 },
    { from: "Miami, FL", to: "New York, NY", distance_miles: 1080 },
    { from: "Atlanta, GA", to: "Philadelphia, PA", distance_miles: 760 },
    { from: "Chicago, IL", to: "Dallas, TX", distance_miles: 967 },
    { from: "Seattle, WA", to: "Los Angeles, CA", distance_miles: 1130 },
    { from: "San Diego, CA", to: "San Francisco, CA", distance_miles: 502 }
]